# Generated by Django 4.1.7 on 2023-02-24 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_processing', 'В обработке'), ('to_work', 'В работу'), ('cancel', 'Отмена'), ('done', 'Выполнена')], max_length=100)),
                ('completion_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=2000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leads', to='core.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
